#  setup.py
#  Opyrix
#
#  Created by Paul Murphy on 8/7/13.
#
"""
    This is a setup.py script generated by py2applet
    
    Usage:
    python setup.py py2app
    """

from setuptools import setup

PLUGIN = ['OpyrixScript.py']
DATA_FILES = []
OPTIONS = {'argv_emulation': False }

setup(
      plugin=PLUGIN,
      data_files=DATA_FILES,
      options={'py2app': OPTIONS},
      setup_requires=['py2app'],
      )
